import { store } from "@/store";

export function loaderDisabled(){
store.commit("changeYatakDagilimLoader",0)
store.commit("changeodaTipiDagilimLoader",0)
store.commit("changeUlkeDagilimLoader",0)
store.commit("changeGecelemeDagilimLoader",0)
store.commit("changeRezAnalizLoader",0)
store.commit("changeIptalAnalizLoader",0)
store.commit("changeGelecekDolulukLoader",0)
store.commit("changeIptalEdilebilirAnalizGunlukLoader",0)
store.commit("changeIptalEdebilirAnalizLoader",0)
store.commit("changeRawDataLoader",0)
store.commit("changeGecmisRezervasyonlarLoader",0)
store.commit("changeKanalRezDagilimLoader",0)
store.commit("changeDolulukLoader",0)
store.commit("changeHaftaDolulukLoader",0)
store.commit("changeAyDolulukLoader",0)
store.commit("changeSonYediAyDolulukLoader",0)
store.commit("changeRezervMiktarLoader",0)
store.commit("changeOnlineRezMiktariLoader",0)
store.commit("changeGecmisRezervasyonDagilimLoader",0)
store.commit("changeChannelTableLoader",0)
}

export function loaderEnabled(){
    store.commit("changeYatakDagilimLoader",1)
    store.commit("changeodaTipiDagilimLoader",1)
    store.commit("changeUlkeDagilimLoader",1)
    store.commit("changeGecelemeDagilimLoader",1)
    store.commit("changeRezAnalizLoader",1)
    store.commit("changeIptalAnalizLoader",1)
    store.commit("changeGelecekDolulukLoader",1)
    store.commit("changeIptalEdilebilirAnalizGunlukLoader",1)
    store.commit("changeIptalEdebilirAnalizLoader",1)
    store.commit("changeRawDataLoader",1)
    store.commit("changeGecmisRezervasyonlarLoader",1)
    store.commit("changeKanalRezDagilimLoader",1)
    store.commit("changeDolulukLoader",1)
    store.commit("changeHaftaDolulukLoader",1)
    store.commit("changeAyDolulukLoader",1)
    store.commit("changeSonYediAyDolulukLoader",1)
    store.commit("changeRezervMiktarLoader",1)
    store.commit("changeOnlineRezMiktariLoader",1)
    store.commit("changeGecmisRezervasyonDagilimLoader",1)
    store.commit("changeChannelTableLoader",1)
    }